final String dbProtocol = "jdbc:sqlite:";

String dbUrl = String.format("%s%s", dbProtocol, ":memory:");  // Base de datos en la memoria
// Algunos centros para agregar a la base de datos.
Object[][] registros = {
    new Object[] {11004866, "IES Castillo de Luna", "pública"},
    new Object[] {11007533, "IES Arroyo Hondo", "pública"},
    new Object[] {11701164, "IES Astaroth", "pública"}
};

try(Connection conn = DriverManager.getConnection(dbUrl)) {

   try(Statement stmt = conn.createStatement()) {
      // Particular de SQLite: respetar la integridad referencial (opcional).
      stmt.execute("PRAGMA foreign_keys = ON");

       stmt.executeUpdate("""
           CREATE TABLE Centro (
               id          INTEGER             PRIMARY KEY,
               nombre      VARCHAR(200)        NOT NULL,
               titularidad CHAR(7)             CHECK (titularidad IN ('pública','privada'))
           );
       """);
       stmt.executeUpdate("""
           CREATE TABLE Estudiante (
               id_estudiante  INTEGER       PRIMARY KEY /* GENERATED BY DEFAULT AS IDENTITY */,
               nombre         VARCHAR(250)  NOT NULL,
               nacimiento     DATE          NOT NULL,
               centro         INTEGER,

               constraint fk_est_cen FOREIGN KEY(centro) REFERENCES Centro(id_centro)
                   ON DELETE SET NULL
                   on UPDATE CASCADE
           );                       
       """);
   }
   catch(SQLException err) {
      err.printStackTrace();
      System.exit(1);
   }
}
